### ISSUE TITLE
PHP Notice when running phpdcd 1.0.2

### ISSUE THREAD

**Issue by etienneq** [sebastianbergmann/php-token-stream#36]
When running phpdcd 1.0.2 (installed using Composer) I get the following PHP notice:

Notice: Undefined offset: -1 in phpunit/php-token-stream/PHP/Token/Stream.php on line 586

Call Stack:
1. {main}() sebastian/phpdcd/phpdcd:0
2. Symfony\Component\Console\Application->run() sebastian/phpdcd/phpdcd:64
3. SebastianBergmann\PHPDCD\CLI\Application->doRun() symfony/console/Symfony/Component/Console/Application.php:124
4. Symfony\Component\Console\Application->doRun() sebastian/phpdcd/src/CLI/Application.php:136
5. Symfony\Component\Console\Application->doRunCommand() symfony/console/Symfony/Component/Console/Application.php:193
6. Symfony\Component\Console\Command\Command->run() symfony/console/Symfony/Component/Console/Application.php:889
7. SebastianBergmann\PHPDCD\CLI\Command->execute() symfony/console/Symfony/Component/Console/Command/Command.php:252
8. SebastianBergmann\PHPDCD\Detector->detectDeadCode() sebastian/phpdcd/src/CLI/Command.php:137
9. SebastianBergmann\PHPDCD\Analyser->analyseFile() sebastian/phpdcd/src/Detector.php:69
10. SebastianBergmann\PHPDCD\Analyser->analyseSourceCode() sebastian/phpdcd/src/Analyser.php:159
11. PHP_Token_Stream->offsetGet() phpunit/php-token-stream/PHP/Token/Stream.php:0

**Comment by sebastianbergmann** [comment]
Should have been fixed by a1228f63dfea8af98efb858aa453d46f7ac24e55.
