### ISSUE TITLE
Fatal error: Class undefined: PHP_Token_WHERE

### ISSUE THREAD

**Issue by digra5319** [sebastianbergmann/php-token-stream#45]
I am trying to run phpunit tests with code coverage but receive the error below which is not one of the Tokens used by Hack at the bottom of https://github.com/sebastianbergmann/php-token-stream/blob/master/src/Token.php

````
Fatal error: Class undefined: PHP_Token_WHERE in phar://phpunit-4.5.0.phar/php-token-stream/Token/Stream.php on line 185
````

After adding the PHP_Token_WHERE class I received more errors from the classes below and added them as well. My concern is that I tried researching theses classes and found no documentation. Are these legitimate classes to add for resolving this error? 

````
class PHP_Token_WHERE extends PHP_Token {}
class PHP_Token_ENUM extends PHP_Token {}
class PHP_Token_JOIN extends PHP_Token {}
class PHP_Token_ONUMBER extends PHP_Token {}
````

**Comment by sebastianbergmann** [comment]
I don't use Hack. If you want Hack tokens added to this package then please send a pull request.

**Comment by sebastianbergmann** [comment]
Either send a pull request that adds all Hack tokens not yet in https://github.com/sebastianbergmann/php-token-stream/blob/master/src/Token.php#L796 or point me to a list of all Hack tokens.

**Comment by sebastianbergmann** [comment]
I do not see a `WHERE` token in https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_tokens.hhi
