### ISSUE TITLE
Class undefined: PHP_Token_WHERE

### ISSUE THREAD

**Issue by firodj** [sebastianbergmann/php-token-stream#51]
I'am using **PHPUnit 4.5.1** and **HipHop VM 3.8.0 (rel)** [*tags/HHVM-3.8.0-0-gbb32f8d645b28561d8491870c44730b9b3f08d35*], and got following errors:

```
Class undefined: PHP_Token_WHERE in /.../vendor/phpunit/php-token-stream/src/Token/Stream.php on line 184
```

see: [https://github.com/facebook/hhvm/issues/5099]

**Comment by GrahamCampbell** [comment]
PHPUnit 4.5.1 isn't supported.

**Comment by GrahamCampbell** [comment]
Only 4.8.3 is supported.
