### ISSUE TITLE
Anonymous classes are still not handled properly

### ISSUE THREAD

**Issue by bwoebi** [sebastianbergmann/php-token-stream#61]
The code is just flat out ignoring anonymous classes. `PHP_Token_Stream::getClasses()` should include the anon classes.

Thus sebastianbergmann/php-code-coverage#373 still exists... [As code coverage learns that there's no code on these lines and thus ignores the coverage of the anonymous classes.]

A simple fix would be just renaming anonymous classes to something à la `anonClass@src/Test.php:5#25` (i.e. "anonClass@$file:$line#$tokenId"), which yields an unique identifier, also useful for readers of the name.

**Comment by sebastianbergmann** [comment]
A pull request would be most welcome :-)

**Comment by sebastianbergmann** [comment]
Looks like this may get fixed along the way while working on #66.

**Comment by sebastianbergmann** [comment]
Hopefully fixed by a6ce111630a5eea291d13c273295853ac1a7bf1f.

@bwoebi Can you have a look?

**Comment by sebastianbergmann** [comment]
a6ce111630a5eea291d13c273295853ac1a7bf1f was released as part of `2.0.0`. Please open a new ticket in case this problem persists.
