### ISSUE TITLE
Getting failed assertion inside PHP_Token_FunctionTest::testGetEndLine

### ISSUE THREAD

**Issue by peter279k** [sebastianbergmann/php-token-stream#80]
As title, I found this failed assertion during `phpunit` tests.

![image](https://user-images.githubusercontent.com/9021747/48311631-8c595d00-e5dd-11e8-8b39-9ea5fd4419bb.png)

## Reproduce issue
- OS: Ubuntu 16.04
- PHP version: `PHP 7.2.11-3+ubuntu16.04.1+deb.sury.org+1 with Xdebug 2.6.1`.
- PHPUnit version: `PHPUnit 7.4.3`.
- Run `phpunit` then it will get this failed assertions message.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
$ ./vendor/bin/phpunit                              
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.1 with Xdebug 2.7.0beta1
Configuration: /usr/local/src/php-token-stream/phpunit.xml

.........................................                         41 / 41 (100%)

Time: 131 ms, Memory: 6.00MB

OK (41 tests, 106 assertions)
```
