### ISSUE TITLE
Uneeded file in git

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/php-token-stream#94]
Thanks to c22d9fe19d7ee8bfbfbba520c736a8545894f21b we now have to use a git snapshot to be able to properly use this project.

Surprize, tarball is **200 time bigger** (from 14K to 2.9M) :(

Looking, I don't see why the "tools" directory is tracked, this are only a copy of some upstream commands (composer, ...) 

Please remove them (and .gitignore them)

**Comment by sebastianbergmann** [comment]
The `tools` directory is not under version control by accident: this is not a bug.

The changes made in c22d9fe19d7ee8bfbfbba520c736a8545894f21b (as well as with similar commits in (hopefully) all of my repositories recently) optimize for the common case: installing a tool or library using Composer. By default, Composer uses the archives that GitHub automatically creates based on tags. The changes made in c22d9fe19d7ee8bfbfbba520c736a8545894f21b makes these archives smaller, meaning users of the libraries and tools in question need to download less.

In contrast to the common use case described above is the less common use case of working on the tool or library in question. I am sorry that you have to deal with larger downloads now, but I will not remove the `tools` directory from version control in any of my repositories.

**Comment by remicollet** [comment]
Things going more crazy everyday....
Shame on PHP world

BTW, this will also affects user of composer with --prefer-sources
