### ISSUE TITLE
PHP 8 and trailing newline in comment token

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-token-stream#95]
* https://github.com/php/php-src/pull/5182
* http://git.php.net/?p=php-src.git;a=commitdiff;h=47cf18ba4ef9fb9df6c3affff8f2a3f5a3f930a8

**Comment by sebastianbergmann** [comment]
This could be the root cause for https://github.com/sebastianbergmann/php-code-coverage/runs/810286407.

**Comment by sebastianbergmann** [comment]
@theseer will (probably) have to adapt [theseer/tokenizer](https://github.com/theseer/tokenizer/) for this as well.

**Comment by theseer** [comment]
Checking...

**Comment by sebastianbergmann** [comment]
The changes made in 19cf736c85bdc610e48b75387b4ac6a8f74c6bb6 re-attach the newline to the comment token and effectively reverse the [change in PHP 8](http://git.php.net/?p=php-src.git;a=commitdiff;h=47cf18ba4ef9fb9df6c3affff8f2a3f5a3f930a8) so that code that uses this component continues to work without change in PHP 8.

**Comment by sebastianbergmann** [comment]
Work on this is not complete.
